# Generated by Django 6.0.2 on 2026-02-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_book_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="date_of_birth",
            new_name="birth",
        ),
        migrations.RenameField(
            model_name="author",
            old_name="date_of_death",
            new_name="death",
        ),
    ]
