# Generated by Django 6.0.2 on 2026-02-06 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_date_of_birth_author_birth_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="birth",
            new_name="date_of_birth",
        ),
        migrations.RenameField(
            model_name="author",
            old_name="death",
            new_name="date_of_death",
        ),
    ]
